services:
  bot:
    build: .
    restart: always
    environment:
      - POSTGRES_URL=postgresql://postgres@db:5432/bot
    depends_on:
      - db

  db:
    image: postgres:16.2
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=bot
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
